name: StarRocks Docker Images CI

env:
  STARROCKS_VERSION: 2.5.2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print version
      run: echo ${{  env.STARROCKS_VERSION  }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --progress plain --tag d87904488/starrocks-starter:${{  env.STARROCKS_VERSION  }}
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{  secrets.DOCKER_USERNAME  }}
        # Password or personal access token used to log against the Docker registry
        password: ${{  secrets.DOCKER_PASSWORD  }}
    - name: Push
      run: docker push d87904488/starrocks-starter:${{  env.STARROCKS_VERSION  }}
